version: "3.8" # Specify Docker Compose version

services:
  bookings-app:
    build: . # Build the image from the current directory (where Dockerfile is located)
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      # - GO111MODULE=on  # Enable Go modules
      - PORT=8080 # Set the port for the Go application
      - DATABASE_URL=mongodb://mongodb:2177/music-api # Example database configuration (if  applicable)
    depends_on:
      - mongodb # Dependency on a database service (if applicable)

  mongodb: # Example database service (if needed)
    image: mongo:latest
