basePath: /
definitions:
  api.Exception:
    properties:
      message:
        type: string
      path:
        type: string
      timestamp:
        type: string
    type: object
  api.Response:
    properties:
      data: {}
      message:
        type: string
    type: object
  authentication.Credentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.TaskRequest:
    properties:
      description:
        type: string
      end_date:
        type: string
      title:
        type: string
    required:
    - title
    type: object
info:
  contact: {}
  description: Swagger API for Golang Project Music Streaming API
  license:
    name: MIT
    url: https://github.com/AthrsonsSilva/music-streaming-api
  termsOfService: http://swagger.io/terms/
  title: Task list Swagger API
  version: "1.0"
paths:
  /api/v1/tasks:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1
        description: page
        in: query
        name: page
        type: integer
      - default: 10
        description: size
        in: query
        name: size
        type: integer
      - default: created_at
        description: field
        in: query
        name: field
        type: string
      - default: -1
        description: direction
        in: query
        name: direction
        type: integer
      - description: searchName
        in: query
        name: searchName
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - tasks
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Task request
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.TaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - tasks
  /api/v1/tasks/{id}:
    delete:
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - tasks
    get:
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - tasks
    put:
      consumes:
      - application/json
      parameters:
      - description: Task request
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.TaskRequest'
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - tasks
  /api/v1/tasks/export-csv:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - tasks
  /api/v1/users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - users
  /api/v1/users/signin:
    post:
      consumes:
      - application/json
      parameters:
      - description: SignUp request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authentication.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - users
  /api/v1/users/signup:
    post:
      consumes:
      - application/json
      parameters:
      - in: formData
        name: email
        type: string
      - in: formData
        name: password
        type: string
      - in: formData
        name: username
        type: string
      - description: File
        in: formData
        name: file
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - users
  /api/v1/users/verify:
    get:
      parameters:
      - description: token
        in: query
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Exception'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.Exception'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Exception'
      tags:
      - users
swagger: "2.0"
