basePath: /
definitions:
  api.Response:
    properties:
      data: {}
      message:
        type: string
    type: object
  authentication.Credentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.AlbumRequest:
    properties:
      artist:
        type: string
      price:
        type: number
      title:
        type: string
    required:
    - artist
    - price
    - title
    type: object
  models.UserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Swagger API for Golang Project Music Streaming API
  license:
    name: MIT
    url: https://github.com/AthrsonsSilva/music-streaming-api
  termsOfService: http://swagger.io/terms/
  title: Music Streaming Swagger API
  version: "1.0"
paths:
  /api/v1/albums:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Find all albums
      tags:
      - albums
    post:
      consumes:
      - application/json
      parameters:
      - description: Album request
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/models.AlbumRequest'
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Creates an album
      tags:
      - albums
  /api/v1/albums/{id}:
    delete:
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Deletes an album
      tags:
      - albums
    get:
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Find one album by ID
      tags:
      - albums
    put:
      consumes:
      - application/json
      parameters:
      - description: Album request
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/models.AlbumRequest'
      - description: Album ID
        in: path
        name: id
        required: true
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Find all albums
      tags:
      - albums
  /api/v1/users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Find one user by ID
      tags:
      - users
  /api/v1/users/signin:
    post:
      consumes:
      - application/json
      parameters:
      - description: SignUp request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authentication.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: SignIn the user and returns a JWT token
      tags:
      - users
  /api/v1/users/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: User request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Creates an user
      tags:
      - users
swagger: "2.0"
