basePath: /
info:
  contact: {}
  description: Swagger API for Golang Project Music Streaming API
  license:
    name: MIT
    url: https://github.com/AthrsonsSilva/music-streaming-api
  termsOfService: http://swagger.io/terms/
  title: Music Streaming Swagger API
  version: "1.0"
paths: {}
swagger: "2.0"
